# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='tracking_pipeline',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x11tracking_pipeline\"\x1e\n\x08KeyPoint\x12\x12\n\x06points\x18\x01 \x03(\x02\x42\x02\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_KEYPOINT = _descriptor.Descriptor(
  name='KeyPoint',
  full_name='tracking_pipeline.KeyPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='tracking_pipeline.KeyPoint.points', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['KeyPoint'] = _KEYPOINT

KeyPoint = _reflection.GeneratedProtocolMessageType('KeyPoint', (_message.Message,), dict(
  DESCRIPTOR = _KEYPOINT,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.KeyPoint)
  ))
_sym_db.RegisterMessage(KeyPoint)


_KEYPOINT.fields_by_name['points'].has_options = True
_KEYPOINT.fields_by_name['points']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
